# class 29

In [2]:
import numpy as np
arr=np.arange(100)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
arr.dtype

dtype('int32')

In [5]:
data=np.random.randn(2,3)

In [6]:
data

array([[ 0.01993099, -0.5399663 , -2.46066965],
       [ 0.12791158, -0.54154533,  0.97044002]])

In [7]:
D=np.arange(64).reshape(4,4,4)

In [8]:
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [9]:
D.ndim

3

In [10]:
ar=np.zeros_like(D) #

In [11]:
ar

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [13]:
ar=np.ones_like(D)

In [14]:
ar

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [18]:
arr2d=np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr2d[3,2]

17

In [20]:
arr2d[3][2]

17

In [21]:
arr3d=np.arange(64).reshape(2,8,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [22]:
arr3d[0][4][1]

17

In [23]:
arr3d=np.arange(64).reshape(4,2,8)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [24]:
arr3d[2,1,2]

42

In [25]:
arr1d=np.arange(20)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
arr1d[3:7]

array([3, 4, 5, 6])

In [27]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr2d[1:5,1:5] # Startrow:endrow,startcolumn:endcoulmn

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [33]:
arr2d[0:5,4:5]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [34]:
arr2d[0:,4] #this is indexing kuin ke sari values nhi di isliye   #slicing me usi shape me aega jis shape orginally h

array([ 4,  9, 14, 19, 24])

In [38]:
ar3d=np.arange(36).reshape(2,3,6)
ar3d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [36]:
ar3d[1,1,5] # indexing

29

In [39]:
ar3d[1,1:2,2:5]

array([[26, 27, 28]])

In [40]:
ar1d=np.arange(20)
ar1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
ar1d.shape

(20,)

In [42]:
a=np.array(ar1d).reshape(4,5)

In [43]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
a=np.array(ar1d).reshape(1,20)

In [45]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [53]:
data=np.arange(100).reshape(10,10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
data%2!=0  #masking

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True]])

In [52]:
data[data%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [60]:
A=np.array(['bob','alice','barbara','john','smith','bob','john','alice','bob','bob'])
A

array(['bob', 'alice', 'barbara', 'john', 'smith', 'bob', 'john', 'alice',
       'bob', 'bob'], dtype='<U7')

In [61]:
A.dtype

dtype('<U7')

In [62]:
data[A=='bob']

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])