# Class 26

In [1]:
with open ('file.txt','r') as f:
    print(f.read())

FileNotFoundError: [Errno 2] No such file or directory: 'file.txt'

In [2]:
with open ('file.txt','w') as f:
    f.write('Hello world')

In [3]:
with open ('file.txt','r') as f:
    print(f.read())

Hello world


In [14]:
import csv
with open("Competition.csv") as f:
    contents_of_f = csv.reader(f)


In [23]:
with open("Competition.csv", "w", newline="") as f:
    data_handler = csv.writer(f, delimiter=",")
    data_handler.writerow(["Year2", "Event2",
    "Winner2"])
    data_handler.writerow(["1995", "Best-Kept Lawn",
    "None"])
    data_handler.writerow(["1999", "Gobstones",
    "Welch National"])

In [24]:
with open("Competition.csv") as f:
    contents_of_f = csv.reader(f)
#     reader_of_f = csv.reader(f)
    potter_competition = []
    for each_line in contents_of_f:
        print( each_line)
# print(potter_competition)

['Year2', 'Event2', 'Winner2']
['1995', 'Best-Kept Lawn', 'None']
['1999', 'Gobstones', 'Welch National']


In [27]:
with open("Competition.csv", "w", newline="") as f:
    data_handler = csv.writer(f)
    data_handler.writerow(["Year2", "Event2",
    "Winner2"])
    data_handler.writerow(["1995", "Best-Kept Lawn",
    "None"])
    data_handler.writerow(["1999", "Gobstones",
    "Welch National"])

In [31]:
#for storing
import json  #for list
alphabet_letters = ["a", "b", "c"]
with open("alphabet_list.json", "w") as f:
    json.dump(alphabet_letters, f)


In [33]:
#for Distionary
customer_29876 = {
"first name": "David",
"last name": "Elliott",
"address": "4803 Wellesley St.",
}
with open("customer_29876.json", "w") as f:
    json.dump(customer_29876, f)

In [34]:
#for retrive
customer_29876 = {
"first name": "David",
"last name": "Elliott",
"address": "4803 Wellesley St.",
}

with open("customer_29876.json") as f:
    customer_29876 = json.load(f)
    
print(customer_29876)
print(customer_29876["last name"])


    

{'first name': 'David', 'last name': 'Elliott', 'address': '4803 Wellesley St.'}
Elliott


# Class 27

In [3]:
import numpy as np


In [4]:
%time # magic function

Wall time: 0 ns


In [9]:
data= np.random.randn(2,3)
data

array([[1.55656389, 0.13382661, 0.16916976],
       [0.89702205, 0.14282031, 2.00995262]])

In [7]:
# data= np.random.randint(2,3)
# data

2

In [11]:
data * 10 #vectorize operation #value increase in all 3 direction

array([[15.56563889,  1.33826606,  1.69169765],
       [ 8.97022054,  1.42820313, 20.09952622]])

In [21]:
arr=np.arange(64).reshape((2,8,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [23]:
arr1=np.arange(64).reshape((2,8,4))

In [24]:
arr * arr1

array([[[   0,    1,    4,    9],
        [  16,   25,   36,   49],
        [  64,   81,  100,  121],
        [ 144,  169,  196,  225],
        [ 256,  289,  324,  361],
        [ 400,  441,  484,  529],
        [ 576,  625,  676,  729],
        [ 784,  841,  900,  961]],

       [[1024, 1089, 1156, 1225],
        [1296, 1369, 1444, 1521],
        [1600, 1681, 1764, 1849],
        [1936, 2025, 2116, 2209],
        [2304, 2401, 2500, 2601],
        [2704, 2809, 2916, 3025],
        [3136, 3249, 3364, 3481],
        [3600, 3721, 3844, 3969]]])