In [1]:
# to check prime number
Num = int(input("Enter a number"))

flag= False

if Num>1:
    for i in range(2,Num):
        if(Num%i==0):
            flag=True
            break
if flag==True:
    print("Number is not prime")
else:
    print("number is  prime")

Enter a number3
number is  prime


In [2]:
# to add two number
Num1 = int(input("Enter a number"))
Num2 = int(input("Enter a number"))
sum=Num1 + Num2
print(f"Sum is :{sum}")

Enter a number2
Enter a number3
Sum is :5


In [3]:
numbers=[1,3,5,6,8,9,11,22,33,44,55,66,77,88,99]
for i in numbers:
    if i%11==0:
        print(f"{i} is divisible by 11")
    else:
        print("{0} is not divisible by 11".format(i))
    

1 is not divisible by 11
3 is not divisible by 11
5 is not divisible by 11
6 is not divisible by 11
8 is not divisible by 11
9 is not divisible by 11
11 is divisible by 11
22 is divisible by 11
33 is divisible by 11
44 is divisible by 11
55 is divisible by 11
66 is divisible by 11
77 is divisible by 11
88 is divisible by 11
99 is divisible by 11


# Password protected marksheet display


In [4]:
username="habib"
password="123"

Username=input("Enter your username : ")

if Username==username:
    Password=input("Enter your password : ")
    if Password==password:
        print("Login Approved")
        
        CC=float(input("Enter your CC marks"))
        DM=float(input("Enter your DM marks"))
        DS=float(input("Enter your DS marks"))
        
        Obtainmarks=CC+DM+DS
        Totalmarks=300
        Result=(Obtainmarks/Totalmarks)*100
        
        print(f"""                               MARKS  SHEET    
        Compilier Construction : {CC}
        Discrete Maths         : {DM}
        Data Science           : {DS}
        
        Obatain Marks = {Obtainmarks}
        Total Marks   = {Totalmarks}
        Grade         = {Result}
        
        """)
        
    else:
        print("Wrong Password")
else:
    print("Wrong Username")
        

Enter your username : habib
Enter your password : 123
Login Approved
Enter your CC marks78
Enter your DM marks98
Enter your DS marks77
                               MARKS  SHEET    
        Compilier Construction : 78.0
        Discrete Maths         : 98.0
        Data Science           : 77.0
        
        Obatain Marks = 253.0
        Total Marks   = 300
        Grade         = 84.33333333333334
        
        


In [5]:
# 1) A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years.
#Ask user for their salary and year of service and print the net bonus amount.

In [6]:
salary=int(input("Enter your salary"))
experience=int(input("Enter your year of services"))
if experience>5:
    bonus=(salary*5)/100
    netbonus=bonus*12
    print("Net Bonus amount is :"+ str(netbonus))
    

Enter your salary89000
Enter your year of services7
Net Bonus amount is :53400.0


In [8]:
units=int(input("Enter your units"))
if units==100:
    print("No charges")
elif units >100 and units<=200:
    bill=(units-100)*5
    print(f"Bill = {bill}")
elif units>200:
    previous=(100)*5
    bill=previous+(units-200)*10
    print(f"Bill = {bill}")
            
else:
    print("Enter right amount")
            


Enter your units400
Bill = 2500


In [9]:
Courses=["Ai","DS","CC","DM"]


In [10]:
Courses

['Ai', 'DS', 'CC', 'DM']

In [11]:
Courses[2]

'CC'

In [12]:
del Courses[3]

In [13]:
Courses

['Ai', 'DS', 'CC']

In [14]:
Courses.insert(2,"Web")

In [15]:
Courses

['Ai', 'DS', 'Web', 'CC']

In [16]:
Courses.remove("CC")

In [17]:
Courses

['Ai', 'DS', 'Web']

In [18]:
Courses.pop(1)

'DS'

In [19]:
square=[] #without
for i in range(1,11):
    sq=i**2
    square.append(sq)
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [20]:
Square=[ i**2 for i in range(1,11)] #with
Square

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [21]:
FN=["habib","Mehtab"]
LN=[" ur rehman"," Ahmed"]
for i in FN:
    for j in LN:
        if FN.index(i)==LN.index(j):
            print(i+j)
        
#NOT SOLVED


habib ur rehman
Mehtab Ahmed


In [22]:
FN=["habib","Mehtab"]
LN=["ur rehman","Ahmed"]
for i in FN:
    print(f"{i} {LN[FN.index(i)]}")

habib ur rehman
Mehtab Ahmed


In [23]:
cars={"Honda":"City","Nissan":"GTR","Toyota":"Carolla"}

In [24]:
cars

{'Honda': 'City', 'Nissan': 'GTR', 'Toyota': 'Carolla'}

In [25]:
type(cars)

dict

In [26]:
cars["Honda"]

'City'

In [27]:
cars["Daihutsu"]="Mira"

In [28]:
cars

{'Honda': 'City', 'Nissan': 'GTR', 'Toyota': 'Carolla', 'Daihutsu': 'Mira'}

In [29]:
del cars["Daihutsu"]

In [30]:
cars

{'Honda': 'City', 'Nissan': 'GTR', 'Toyota': 'Carolla'}

In [31]:
for i in cars:
    print(i)

Honda
Nissan
Toyota


In [32]:
for i in cars.values():
    print(i)

City
GTR
Carolla


In [33]:
for i in cars.items():
    print(i)

('Honda', 'City')
('Nissan', 'GTR')
('Toyota', 'Carolla')


In [34]:
Cars=[{"Honda":"City"},{"Niassan":"GTR"}]


In [35]:
Cars

[{'Honda': 'City'}, {'Niassan': 'GTR'}]

In [36]:
Cars[0]

{'Honda': 'City'}

In [37]:
Cars[0]["Honda"]

'City'

In [38]:
count=0
Total=0
while count<=100:
    Total=Total+count
    count+=1
    
print(Total)    


5050


In [1]:
# lst=[10, 99, 98, 85, 45, 59, 65, 66, 76, 12, 35, 13, 100, 80, 95]
# while lst[i]:
#         if i.real==100:
#             print(f"There is a 100 at index no: {lst.index(i)}")
            

In [ ]:
i=0
lst1=[10, 99, 98, 85, 45, 59, 65, 66, 76, 12, 35, 13, 100, 80, 95]
while i<len(lst1):
        if lst1[i]==100:
            print(f"There is a 100 at index no: {str(i)}")
            i=i+1
            
            

In [1]:
count=0
num=[10, 99, 98, 85, 45, 59, 65, 66, 76, 12, 35, 13, 100, 80, 95]
while count<len(num):
    print(num[count])
    count+=1

10
99
98
85
45
59
65
66
76
12
35
13
100
80
95


In [2]:
count=0
num=[10, 99, 98, 85, 45, 59, 65, 66, 76, 12, 35, 13, 100, 80, 95]
while count<len(num):
    if (num[count]==100):
        print(f"index : {str(count)}")
    count+=1

index : 12


In [ ]:
#print even number using while loop

In [ ]:
count=0
num=[1,2,3,4,5,6,7,8,9,10]
while count<len(num):
    if num[count]%2==0:
        print(f"{num[count]} is an even number")
        count+=1

In [ ]:
print("hello")

In [8]:
def Calculator(num1,num2):
    print("""
    Press 1 for Sub
    Press 2 for Add
    Press 3 for Div""")
    Num=int(input("Enter number to execute"))
    if Num==1:
        sub=num1-num2
        print(f"Answer : {sub}")
    elif Num==2:
        add=num1+num2
        print(f"Answer : {add}")
    elif Num==3:
        div=num1/num2
        print(f"Answer : {div}")
    else:
        print("Enter valid number")
        
    
    

In [11]:
Calculator(4,7)


    Press 1 for Sub
    Press 2 for Add
    Press 3 for Div
Enter number to execute1
Answer : -3


In [5]:
def square(num):
    global sqr
    sqr=num**2
    print(sqr)

In [6]:
square(2)

4


In [3]:
sqr=81

In [4]:

def sq(num):
    print(sqr)

In [5]:
sq(3)

81


In [6]:
def make_sandwich(*items):#arbritary keywords
    print(items)
    

In [7]:
make_sandwich("bread","egg","chicken","mayo","sauce")

('bread', 'egg', 'chicken', 'mayo', 'sauce')


In [37]:
class Cars():
    def __init__(self,model,make,year,engine,doors):
        self.model=model
        self.make=make
        self.year=year
        self.engine=engine
        self.doors=doors
        
    def Drive(self):
        print(f"{self.model} is driving")
    
    def set_model(self,model):
        self.model=model
        

In [38]:
c1=Cars("City","Honda",2022,"Turbo",4)

In [39]:
c1.make

'Honda'

In [40]:
c1.year


2022

In [41]:
c1.Drive()

City is driving


In [42]:
c1.set_model("Civic")

In [20]:
c1.model

'Civic'

In [43]:
class Electriccar(Cars):
    def __init__(self,model,make,year,engine,doors,size_of_battery,charger_volt):
        super().__init__(model,make,year,engine,doors)
        self.size_of_battery=size_of_battery
        self.charger_volt=charger_volt
        
    

In [44]:
ec1=Electriccar("City","Honda",2022,"TV8",4,"big",160)

In [45]:
ec1.make

'Honda'

In [46]:
ec1.engine

'TV8'

In [47]:
ec1.size_of_battery

'big'

In [52]:
class Electriccar1(Cars):
    def __init__(self,model,make,year,engine,doors,size_of_battery,charger_volt):
        super().__init__(model,make,year,engine,doors)
        self.size_of_battery=size_of_battery
        self.charger_volt=charger_volt

In [53]:
ec2=Electriccar1("City","Honda",2022,"TV8",4,"big",160)

In [54]:
ec2.Drive()

City is driving


In [55]:
ec2.make

'Honda'

In [1]:
try:
    n=int(input("Enter n number"))
    d=int(input("Enter d number"))
    A=n/d
    print(A)
except ZeroDivisionError:
    print("can't divided by zero")
except ValueError:
    print("only integer")

print("Hello World")

Enter n number3
Enter d number0
can't divided by zero
Hello World


In [3]:
try:
    n=int(input("Enter n number"))
    d=int(input("Enter d number"))
    A=n/d
    print(A)
except:
    print("Error is caught")
print("Hello World")

Enter n numberg
Error is caught
Hello World


In [7]:
try:
    n=int(input("Enter n number"))
    d=int(input("Enter d number"))
    A=n/d
    print(A)
except ZeroDivisionError:
    print("can't divided by zero")
except ValueError:
    print("only integer")



finally:
    print("always print")

print("Hello World")

Enter n number0
Enter d number0
can't divided by zero
always print
Hello World


In [8]:
class student():
    def __init__(self,name,age):
        if age>80 or age<16:
            raise Exception('age can not be greater then 80 and less then 16')
        self.name=name
        self.age=age

In [9]:
s1=student("habib",12)

Exception: age can not be greater then 80 and less then 16

In [10]:
with open('file.txt','w') as f:
    f.write("Hello World!")
    

In [12]:
with open('file.txt','r') as f:
    print(f.read())

Hello World!


In [15]:
with open('file.txt','w+') as f:
    f.write("Hello World!")
    f.seek(0)
    print(f.read())

Hello World!


In [17]:
with open('file.txt','a') as f:
    f.write("i am habib ur rehman")

In [18]:
with open('file.txt','r') as f:
    print(f.read())

Hello World!i am habib ur rehman


In [26]:
import csv
with open('comp.csv','w') as f:
    a= csv.writer(f)
    a.writerows(['habib','1','2000'])

In [29]:
import csv
with open('ax.csv') as f:
    a= csv.reader(f)
    for i in a:
        print(i)

['habib', '10', '2']
['ali', '3', '9']
['ahmed', '1', '8']


In [31]:
with open("Competition.csv","w") as f:
    Data=csv.writer(f)
    Data.writerow(["Burhan","50000"])
    Data.writerow(["Burhan1","30000"])
    Data.writerow(["Burhan1","80000"])

In [32]:
with open("Competition.csv") as f:
    data=csv.reader(f)
    for i in data:
        print(i)

['Burhan', '50000']
[]
['Burhan1', '30000']
[]
['Burhan1', '80000']
[]


In [35]:
import json
ab=['a',"b",'c','d']
with open("new.json","w") as f:
    data=json.dump(ab,f)

In [38]:
with open("new.json","r") as f:
    data=json.load(f)
    print(data)

['a', 'b', 'c', 'd']


In [39]:
import numpy as np

In [40]:
data=np.random.randn(4,4)

In [41]:
print(data)

[[-1.72378509 -1.42340965  1.34558283 -0.8501032 ]
 [-1.70866157 -0.59340879 -0.92669799  0.22139915]
 [ 0.07563878 -0.24825934  0.04330624  0.58631183]
 [-0.83436984  1.1736252   0.68797851  1.6512548 ]]


In [43]:
data.reshape(2,2,4)

array([[[-1.72378509, -1.42340965,  1.34558283, -0.8501032 ],
        [-1.70866157, -0.59340879, -0.92669799,  0.22139915]],

       [[ 0.07563878, -0.24825934,  0.04330624,  0.58631183],
        [-0.83436984,  1.1736252 ,  0.68797851,  1.6512548 ]]])